[package]
name = "clap-subcommands"
authors = ["Keith Sharp <kms@passback.co.uk"]
description = "Experiment with Clap subcommands and args."
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }