[package]
name = "rust-experiments"
authors = ["Keith Sharp <kms@passback.co.uk"]
description = "Small example and test programs in Rust."
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
aws-arn = "0.3"
aws-config = "0.55"
aws-sdk-ec2 = "0.27"
aws-sdk-iam = "0.27"
aws-sdk-s3 = "0.27"
aws-sdk-sqs = "0.27"
aws-types = "0.55"
base64 = "0.21"
clap = { version = "4.1", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.7"
uuid = { version = "1.3", features = ["v4", "fast-rng", "macro-diagnostics"]}
