[package]
name = "rust-experiments"
authors = ["Keith Sharp <kms@passback.co.uk"]
description = "Small example and test programs in Rust."
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
aws-config = "0.54.1"
aws-sdk-ec2 = "0.24.0"
aws-sdk-s3 = "0.24.0"
base64 = "0.21.0"
clap = { version = "4.1.4", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.38"
tokio = { version = "1", features = ["full"] }
toml = "0.7.1"
uuid = { version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics"]}
