[package]
name = "rust-experiments"
authors = ["Keith Sharp <kms@passback.co.uk"]
description = "Small example and test programs in Rust."
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.48.0"
aws-sdk-ec2 = "0.18.0"
clap = { version = "3.2.20", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
