[package]
name = "read-toml"
authors = ["Keith Sharp <kms@passback.co.uk"]
description = "Read values from a TOML formatted file."
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
toml = "0.7"